### ISSUE TITLE
LICENSE informations?

### ISSUE THREAD

**Issue by mariusmotea** [ermos/hue-icon#1]
Hi,

I want to implement the icons from this repo in [diyHue](https://github.com/diyhue/diyHue) project. Do we comply with the license?

Thanks.

**Comment by ermos** [comment]
Hi @mariusmotea,

This icons derived from Philips Hue Developer Program.

Usages of this icons are subject to Signify's property.

You can find this pack here with license :

https://developers.meethue.com/develop/application-design-guidance/icon-pack/

"Note: It is only allowed to use these images in combination with Hue products, and no other projects. Please take care that the right icons are associated with the right products. Applications can detect the archetype, model, type and friendly name of the devices present in the Hue eco-system via the Hue API."

I hope I helped you.

**Comment by mariusmotea** [comment]
Sure, Thanks!
